[project]
name = "classificationbanner"
version = "0.1.0"
description = "Windows Classification Bar"
readme = "README.md"
requires-python = ">=3.14"
dependencies = ["pyinstaller>=6.17.0", "pywin32>=311", "screeninfo>=0.8.1"]
license = { file = "LICENSE" }
