# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python 3.14
        uses: actions/setup-python@v6.1.0
        with:
          python-version: "3.14"
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Install dependencies
        run: |
          uv sync
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          uv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          uv run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          uv run pytest --cov --cov-branch --cov-report=xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: 192d-Cyberspace-Control-Squadron/ClassificationBanner
      - name: Build
        shell: pwsh
        run: uv run pyinstaller --onefile --noconsole --distpath=.\dist\Windows\ --paths=.\src\Windows --name ClassificationBanner .\src\Windows\main.py

      - name: Copy Installer
        run: |
          Get-ChildItem ".\ClassificationBanner_Install" | ForEach-Object {
            Copy-Item $_.FullName .\dist\Windows -Recurse
          }
        shell: pwsh

      - name: Copy Group Policy Objects
        run: |
          Get-ChildItem ".\src\Windows\Group Policy" | ForEach-Object {
            Copy-Item $_.FullName .\dist\Windows\SupportFiles -Recurse
          }
        shell: pwsh

      - name: Move ClassificationBanner.exe
        run: |
          Move-Item .\dist\Windows\ClassificationBanner.exe .\dist\Windows\Files\ClassificationBanner.exe
        shell: pwsh

      - name: Update Version in installer
        run: |
          $Version = "${{github.ref_name}}"
          (Get-Content ".\dist\Windows\Invoke-AppDeployToolkit.ps1") -replace "AppVersion\s*=.*", "AppVersion                  = `'$($Version.Substring(1))`'" | Set-Content ".\dist\Windows\Invoke-AppDeployToolkit.ps1" -Force
        shell: pwsh
      - name: Compress Archive
        run: |
          Compress-Archive -Path ".\dist\Windows\" -DestinationPath ".\dist\ClassificationBanner-${{github.ref_name}}.zip"
        shell: pwsh
      - name: Package build output
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          $zipName = ".\dist\ClassificationBanner-${{ github.ref_name }}.zip"
          echo "ZIP_NAME=$zipName" | Out-File -FilePath $env:GITHUB_ENV -Append

      # Create GitHub Release when this run was triggered by a tag
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }} # e.g. v1.2.3
          name: ${{ github.ref_name }} # release title
          generate_release_notes: true
          files: dist/ClassificationBanner-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
